# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = %(here)s/alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file to be detected
# sourceless = false

# version location specification; this defaults to alembic/versions.
# When using multiple version directories, initial revisions must specify --version-path
version_locations = %(here)s/alembic/versions

# the output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

# Target database URL for PostgreSQL
sqlalchemy.url = postgresql+asyncpg://tourism_user:tourism_password@postgres:5432/tourism_db


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.

[logging]
default_level = INFO

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
